openapi: 3.2.0
info:
  title: Tandoor Open Data FDC API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Open Data FDC
paths:
  /api/open-data-FDC/{id}/:
    get:
      operationId: apiOpenDataFDCRetrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - Open Data FDC
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: No response body
      summary: Api open data FDC retrieve
      x-summary-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
