openapi: 3.2.0
info:
  title: Tandoor View Log API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: View Log
paths:
  /api/view-log/:
    get:
      operationId: apiViewLogList
      description: logs request counts to redis cache total/per user/
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - View Log
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedViewLogList'
          description: ''
      summary: Api view log list
      x-summary-source: derived
    post:
      operationId: apiViewLogCreate
      description: logs request counts to redis cache total/per user/
      tags:
      - View Log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ViewLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ViewLog'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewLog'
          description: ''
      summary: Api view log create
      x-summary-source: derived
  /api/view-log/{id}/:
    get:
      operationId: apiViewLogRetrieve
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this view log.
        required: true
      tags:
      - View Log
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewLog'
          description: ''
      summary: Api view log retrieve
      x-summary-source: derived
    put:
      operationId: apiViewLogUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this view log.
        required: true
      tags:
      - View Log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ViewLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ViewLog'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewLog'
          description: ''
      summary: Api view log update
      x-summary-source: derived
    patch:
      operationId: apiViewLogPartialUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this view log.
        required: true
      tags:
      - View Log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedViewLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedViewLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedViewLog'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewLog'
          description: ''
      summary: Api view log partial update
      x-summary-source: derived
    delete:
      operationId: apiViewLogDestroy
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this view log.
        required: true
      tags:
      - View Log
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api view log destroy
      x-summary-source: derived
components:
  schemas:
    PaginatedViewLogList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/ViewLog'
        timestamp:
          type: string
          format: date-time
    ViewLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        recipe:
          type: integer
        created_by:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - created_by
      - recipe
    PatchedViewLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        recipe:
          type: integer
        created_by:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
