openapi: 3.2.0
info:
  title: Tandoor Open Data Version API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Open Data Version
paths:
  /api/open-data-version/:
    get:
      operationId: apiOpenDataVersionList
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Open Data Version
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOpenDataVersionList'
          description: ''
      summary: Api open data version list
      x-summary-source: derived
    post:
      operationId: apiOpenDataVersionCreate
      tags:
      - Open Data Version
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenDataVersion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpenDataVersion'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OpenDataVersion'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataVersion'
          description: ''
      summary: Api open data version create
      x-summary-source: derived
  /api/open-data-version/{id}/:
    get:
      operationId: apiOpenDataVersionRetrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data version.
        required: true
      tags:
      - Open Data Version
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataVersion'
          description: ''
      summary: Api open data version retrieve
      x-summary-source: derived
    put:
      operationId: apiOpenDataVersionUpdate
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data version.
        required: true
      tags:
      - Open Data Version
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenDataVersion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpenDataVersion'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OpenDataVersion'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataVersion'
          description: ''
      summary: Api open data version update
      x-summary-source: derived
    patch:
      operationId: apiOpenDataVersionPartialUpdate
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data version.
        required: true
      tags:
      - Open Data Version
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataVersion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataVersion'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataVersion'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataVersion'
          description: ''
      summary: Api open data version partial update
      x-summary-source: derived
    delete:
      operationId: apiOpenDataVersionDestroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data version.
        required: true
      tags:
      - Open Data Version
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api open data version destroy
      x-summary-source: derived
components:
  schemas:
    PatchedOpenDataVersion:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        code:
          type: string
          maxLength: 16
        comment:
          type: string
    PaginatedOpenDataVersionList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/OpenDataVersion'
        timestamp:
          type: string
          format: date-time
    OpenDataVersion:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        code:
          type: string
          maxLength: 16
        comment:
          type: string
      required:
      - code
      - name
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
