openapi: 3.2.0
info:
  title: Tandoor User Space API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: User Space
paths:
  /api/user-space/:
    get:
      operationId: apiUserSpaceList
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: query
        name: internal_note
        schema:
          type: string
        description: text field to store information about the invite link
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - User Space
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserSpaceList'
          description: ''
      summary: Api user space list
      x-summary-source: derived
  /api/user-space/{id}/:
    get:
      operationId: apiUserSpaceRetrieve
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user space.
        required: true
      tags:
      - User Space
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSpace'
          description: ''
      summary: Api user space retrieve
      x-summary-source: derived
    put:
      operationId: apiUserSpaceUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user space.
        required: true
      tags:
      - User Space
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSpace'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserSpace'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserSpace'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSpace'
          description: ''
      summary: Api user space update
      x-summary-source: derived
    patch:
      operationId: apiUserSpacePartialUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user space.
        required: true
      tags:
      - User Space
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserSpace'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserSpace'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserSpace'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSpace'
          description: ''
      summary: Api user space partial update
      x-summary-source: derived
    delete:
      operationId: apiUserSpaceDestroy
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user space.
        required: true
      tags:
      - User Space
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api user space destroy
      x-summary-source: derived
  /api/user-space/all_personal/:
    get:
      operationId: apiUserSpaceAllPersonalList
      description: 'return all userspaces for the user requesting the endpoint

        :param request:

        :return:'
      tags:
      - User Space
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSpace'
          description: ''
      summary: Api user space all personal list
      x-summary-source: derived
  /api/user-space/batch_update/:
    put:
      operationId: apiUserSpaceBatchUpdateUpdate
      description: logs request counts to redis cache total/per user/
      tags:
      - User Space
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSpaceBatchUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserSpaceBatchUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserSpaceBatchUpdate'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSpaceBatchUpdate'
          description: ''
      summary: Api user space batch update update
      x-summary-source: derived
components:
  schemas:
    PatchedUserSpace:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        space:
          type: integer
          readOnly: true
        groups:
          type: array
          items:
            $ref: '#/components/schemas/Group'
        household:
          allOf:
          - $ref: '#/components/schemas/Household'
        active:
          type: boolean
        internal_note:
          type:
          - string
          - 'null'
        invite_link:
          type:
          - integer
          - 'null'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    Household:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - name
      - updated_at
    Group:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          readOnly: true
      required:
      - name
    PaginatedUserSpaceList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/UserSpace'
        timestamp:
          type: string
          format: date-time
    UserSpace:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        space:
          type: integer
          readOnly: true
        groups:
          type: array
          items:
            $ref: '#/components/schemas/Group'
        household:
          allOf:
          - $ref: '#/components/schemas/Household'
        active:
          type: boolean
        internal_note:
          type:
          - string
          - 'null'
        invite_link:
          type:
          - integer
          - 'null'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - groups
      - invite_link
      - space
      - updated_at
      - user
    UserSpaceBatchUpdate:
      type: object
      properties:
        user_spaces:
          type: array
          items:
            type: integer
        household:
          type:
          - integer
          - 'null'
        group_set:
          type: array
          items:
            type: integer
      required:
      - group_set
      - user_spaces
    User:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        display_name:
          type: string
          readOnly: true
        is_staff:
          type: boolean
          readOnly: true
          title: Staff status
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          readOnly: true
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
        is_active:
          type: boolean
          readOnly: true
          title: Active
          description: Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
      required:
      - display_name
      - is_active
      - is_staff
      - is_superuser
      - username
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
