openapi: 3.2.0
info:
  title: Tandoor Open Data Property API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Open Data Property
paths:
  /api/open-data-property/:
    get:
      operationId: apiOpenDataPropertyList
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Open Data Property
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOpenDataPropertyList'
          description: ''
      summary: Api open data property list
      x-summary-source: derived
    post:
      operationId: apiOpenDataPropertyCreate
      tags:
      - Open Data Property
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenDataProperty'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpenDataProperty'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OpenDataProperty'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataProperty'
          description: ''
      summary: Api open data property create
      x-summary-source: derived
  /api/open-data-property/{id}/:
    get:
      operationId: apiOpenDataPropertyRetrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data property.
        required: true
      tags:
      - Open Data Property
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataProperty'
          description: ''
      summary: Api open data property retrieve
      x-summary-source: derived
    put:
      operationId: apiOpenDataPropertyUpdate
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data property.
        required: true
      tags:
      - Open Data Property
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenDataProperty'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpenDataProperty'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OpenDataProperty'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataProperty'
          description: ''
      summary: Api open data property update
      x-summary-source: derived
    patch:
      operationId: apiOpenDataPropertyPartialUpdate
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data property.
        required: true
      tags:
      - Open Data Property
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataProperty'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataProperty'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataProperty'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataProperty'
          description: ''
      summary: Api open data property partial update
      x-summary-source: derived
    delete:
      operationId: apiOpenDataPropertyDestroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data property.
        required: true
      tags:
      - Open Data Property
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api open data property destroy
      x-summary-source: derived
components:
  schemas:
    OpenDataVersion:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        code:
          type: string
          maxLength: 16
        comment:
          type: string
      required:
      - code
      - name
    PaginatedOpenDataPropertyList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/OpenDataProperty'
        timestamp:
          type: string
          format: date-time
    OpenDataProperty:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        version:
          $ref: '#/components/schemas/OpenDataVersion'
        slug:
          type: string
          maxLength: 128
        name:
          type: string
          maxLength: 128
        unit:
          type: string
          maxLength: 16
        fdc_id:
          type:
          - integer
          - 'null'
          maximum: 2147483647
          minimum: -2147483648
        comment:
          type: string
        created_by:
          type: string
          readOnly: true
      required:
      - created_by
      - name
      - slug
      - version
    PatchedOpenDataProperty:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        version:
          $ref: '#/components/schemas/OpenDataVersion'
        slug:
          type: string
          maxLength: 128
        name:
          type: string
          maxLength: 128
        unit:
          type: string
          maxLength: 16
        fdc_id:
          type:
          - integer
          - 'null'
          maximum: 2147483647
          minimum: -2147483648
        comment:
          type: string
        created_by:
          type: string
          readOnly: true
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
