openapi: 3.2.0
info:
  title: Tandoor Switch Active Space API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Switch Active Space
paths:
  /api/switch-active-space/{spaceId}/:
    get:
      operationId: apiSwitchActiveSpaceRetrieve
      description: api endpoint to switch space function
      parameters:
      - in: path
        name: spaceId
        schema:
          type: integer
        required: true
      tags:
      - Switch Active Space
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: No response body
      summary: Api switch active space retrieve
      x-summary-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
