openapi: 3.2.0
info:
  title: Tandoor Import Log API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Import Log
paths:
  /api/import-log/:
    get:
      operationId: apiImportLogList
      description: logs request counts to redis cache total/per user/
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Import Log
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedImportLogList'
          description: ''
      summary: Api import log list
      x-summary-source: derived
    post:
      operationId: apiImportLogCreate
      description: logs request counts to redis cache total/per user/
      tags:
      - Import Log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ImportLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ImportLog'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportLog'
          description: ''
      summary: Api import log create
      x-summary-source: derived
  /api/import-log/{id}/:
    get:
      operationId: apiImportLogRetrieve
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this import log.
        required: true
      tags:
      - Import Log
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportLog'
          description: ''
      summary: Api import log retrieve
      x-summary-source: derived
    put:
      operationId: apiImportLogUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this import log.
        required: true
      tags:
      - Import Log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ImportLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ImportLog'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportLog'
          description: ''
      summary: Api import log update
      x-summary-source: derived
    patch:
      operationId: apiImportLogPartialUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this import log.
        required: true
      tags:
      - Import Log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedImportLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedImportLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedImportLog'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportLog'
          description: ''
      summary: Api import log partial update
      x-summary-source: derived
    delete:
      operationId: apiImportLogDestroy
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this import log.
        required: true
      tags:
      - Import Log
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api import log destroy
      x-summary-source: derived
components:
  schemas:
    PatchedImportLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        type:
          type: string
          maxLength: 32
        msg:
          type: string
        running:
          type: boolean
        keyword:
          allOf:
          - $ref: '#/components/schemas/Keyword'
          readOnly: true
        total_recipes:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        imported_recipes:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        created_by:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
    PaginatedImportLogList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/ImportLog'
        timestamp:
          type: string
          format: date-time
    Keyword:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 64
        label:
          type: string
          readOnly: true
        description:
          type: string
        parent:
          type: integer
          readOnly: true
        numchild:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        full_name:
          type: string
          description: 'Returns a string representation of a tree node and it''s ancestors,

            e.g. ''Cuisine > Asian > Chinese > Catonese''.'
          readOnly: true
      required:
      - created_at
      - full_name
      - label
      - name
      - numchild
      - parent
      - updated_at
    ImportLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        type:
          type: string
          maxLength: 32
        msg:
          type: string
        running:
          type: boolean
        keyword:
          allOf:
          - $ref: '#/components/schemas/Keyword'
          readOnly: true
        total_recipes:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        imported_recipes:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        created_by:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - created_by
      - keyword
      - type
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
