openapi: 3.2.0
info:
  title: Tandoor Open Data Unit API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Open Data Unit
paths:
  /api/open-data-unit/:
    get:
      operationId: apiOpenDataUnitList
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Open Data Unit
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOpenDataUnitList'
          description: ''
      summary: Api open data unit list
      x-summary-source: derived
    post:
      operationId: apiOpenDataUnitCreate
      tags:
      - Open Data Unit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenDataUnit'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpenDataUnit'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OpenDataUnit'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataUnit'
          description: ''
      summary: Api open data unit create
      x-summary-source: derived
  /api/open-data-unit/{id}/:
    get:
      operationId: apiOpenDataUnitRetrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data unit.
        required: true
      tags:
      - Open Data Unit
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataUnit'
          description: ''
      summary: Api open data unit retrieve
      x-summary-source: derived
    put:
      operationId: apiOpenDataUnitUpdate
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data unit.
        required: true
      tags:
      - Open Data Unit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenDataUnit'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpenDataUnit'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OpenDataUnit'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataUnit'
          description: ''
      summary: Api open data unit update
      x-summary-source: derived
    patch:
      operationId: apiOpenDataUnitPartialUpdate
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data unit.
        required: true
      tags:
      - Open Data Unit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataUnit'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataUnit'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOpenDataUnit'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenDataUnit'
          description: ''
      summary: Api open data unit partial update
      x-summary-source: derived
    delete:
      operationId: apiOpenDataUnitDestroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this open data unit.
        required: true
      tags:
      - Open Data Unit
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api open data unit destroy
      x-summary-source: derived
components:
  schemas:
    OpenDataVersion:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        code:
          type: string
          maxLength: 16
        comment:
          type: string
      required:
      - code
      - name
    PatchedOpenDataUnit:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        version:
          $ref: '#/components/schemas/OpenDataVersion'
        slug:
          type: string
          maxLength: 128
        name:
          type: string
          maxLength: 128
        plural_name:
          type: string
          maxLength: 128
        base_unit:
          $ref: '#/components/schemas/BaseUnitEnum'
        type:
          $ref: '#/components/schemas/OpenDataUnitTypeEnum'
        comment:
          type: string
        created_by:
          type: string
          readOnly: true
    BaseUnitEnum:
      enum:
      - g
      - kg
      - ounce
      - pound
      - ml
      - l
      - fluid_ounce
      - pint
      - quart
      - gallon
      - tbsp
      - tsp
      - us_cup
      - imperial_fluid_ounce
      - imperial_pint
      - imperial_quart
      - imperial_gallon
      - imperial_tbsp
      - imperial_tsp
      type: string
      description: '* `g` - g

        * `kg` - kg

        * `ounce` - ounce

        * `pound` - pound

        * `ml` - ml

        * `l` - l

        * `fluid_ounce` - fluid_ounce

        * `pint` - pint

        * `quart` - quart

        * `gallon` - gallon

        * `tbsp` - tbsp

        * `tsp` - tsp

        * `us_cup` - US Cup

        * `imperial_fluid_ounce` - imperial fluid ounce

        * `imperial_pint` - imperial pint

        * `imperial_quart` - imperial quart

        * `imperial_gallon` - imperial gallon

        * `imperial_tbsp` - imperial tbsp

        * `imperial_tsp` - imperial tsp'
    OpenDataUnit:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        version:
          $ref: '#/components/schemas/OpenDataVersion'
        slug:
          type: string
          maxLength: 128
        name:
          type: string
          maxLength: 128
        plural_name:
          type: string
          maxLength: 128
        base_unit:
          $ref: '#/components/schemas/BaseUnitEnum'
        type:
          $ref: '#/components/schemas/OpenDataUnitTypeEnum'
        comment:
          type: string
        created_by:
          type: string
          readOnly: true
      required:
      - created_by
      - name
      - slug
      - type
      - version
    OpenDataUnitTypeEnum:
      enum:
      - WEIGHT
      - VOLUME
      - OTHER
      type: string
      description: '* `WEIGHT` - weight

        * `VOLUME` - volume

        * `OTHER` - other'
    PaginatedOpenDataUnitList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/OpenDataUnit'
        timestamp:
          type: string
          format: date-time
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
