openapi: 3.2.0
info:
  title: Tandoor Enterprise Social Keyword API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Enterprise Social Keyword
paths:
  /api/enterprise-social-keyword/:
    get:
      operationId: apiEnterpriseSocialKeywordList
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: query
        name: limit
        schema:
          type: string
        description: limit number of entries to return
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: query
        schema:
          type: string
        description: lookup if query string is contained within the name, case insensitive
      - in: query
        name: random
        schema:
          type: string
        description: randomly orders entries (only works together with limit)
      - in: query
        name: root
        schema:
          type: integer
        description: Return first level children of {obj} with ID [int].  Integer 0 will return root {obj}s.
      - in: query
        name: root_tree
        schema:
          type: integer
        description: Return all items belonging to the tree of the given {obj} id
      - in: query
        name: tree
        schema:
          type: integer
        description: Return all self and children of {obj} with ID [int].
      - in: query
        name: updated_at
        schema:
          type: string
        description: if model has an updated_at timestamp, filter only models updated at or after datetime
      tags:
      - Enterprise Social Keyword
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedKeywordList'
          description: ''
      summary: Api enterprise social keyword list
      x-summary-source: derived
    post:
      operationId: apiEnterpriseSocialKeywordCreate
      description: logs request counts to redis cache total/per user/
      tags:
      - Enterprise Social Keyword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Keyword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Keyword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Keyword'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Keyword'
          description: ''
      summary: Api enterprise social keyword create
      x-summary-source: derived
  /api/enterprise-social-keyword/{id}/:
    get:
      operationId: apiEnterpriseSocialKeywordRetrieve
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      tags:
      - Enterprise Social Keyword
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Keyword'
          description: ''
      summary: Api enterprise social keyword retrieve
      x-summary-source: derived
    put:
      operationId: apiEnterpriseSocialKeywordUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      tags:
      - Enterprise Social Keyword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Keyword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Keyword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Keyword'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Keyword'
          description: ''
      summary: Api enterprise social keyword update
      x-summary-source: derived
    patch:
      operationId: apiEnterpriseSocialKeywordPartialUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      tags:
      - Enterprise Social Keyword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedKeyword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedKeyword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedKeyword'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Keyword'
          description: ''
      summary: Api enterprise social keyword partial update
      x-summary-source: derived
    delete:
      operationId: apiEnterpriseSocialKeywordDestroy
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      tags:
      - Enterprise Social Keyword
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api enterprise social keyword destroy
      x-summary-source: derived
  /api/enterprise-social-keyword/{id}/cascading/:
    get:
      operationId: apiEnterpriseSocialKeywordCascadingList
      description: get a paginated list of objects that will be cascaded (deleted) when deleting the selected object
      parameters:
      - in: query
        name: cache
        schema:
          type: boolean
          default: true
        description: If results can be cached or not
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Enterprise Social Keyword
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedGenericModelReferenceList'
          description: ''
      summary: Api enterprise social keyword cascading list
      x-summary-source: derived
  /api/enterprise-social-keyword/{id}/merge/{target}/:
    put:
      operationId: apiEnterpriseSocialKeywordMergeUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      - in: path
        name: target
        schema:
          type: integer
        description: The ID of the {obj} you want to merge with.
        required: true
      tags:
      - Enterprise Social Keyword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Keyword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Keyword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Keyword'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Keyword'
          description: ''
      summary: Api enterprise social keyword merge update
      x-summary-source: derived
  /api/enterprise-social-keyword/{id}/move/{parent}/:
    put:
      operationId: apiEnterpriseSocialKeywordMoveUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      - in: path
        name: parent
        schema:
          type: integer
        description: The ID of the desired parent of the {obj}.
        required: true
      tags:
      - Enterprise Social Keyword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Keyword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Keyword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Keyword'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Keyword'
          description: ''
      summary: Api enterprise social keyword move update
      x-summary-source: derived
  /api/enterprise-social-keyword/{id}/nulling/:
    get:
      operationId: apiEnterpriseSocialKeywordNullingList
      description: get a paginated list of objects where the selected object will be removed whe its deleted
      parameters:
      - in: query
        name: cache
        schema:
          type: boolean
          default: true
        description: If results can be cached or not
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Enterprise Social Keyword
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedGenericModelReferenceList'
          description: ''
      summary: Api enterprise social keyword nulling list
      x-summary-source: derived
  /api/enterprise-social-keyword/{id}/protecting/:
    get:
      operationId: apiEnterpriseSocialKeywordProtectingList
      description: get a paginated list of objects that are protecting the selected object form being deleted
      parameters:
      - in: query
        name: cache
        schema:
          type: boolean
          default: true
        description: If results can be cached or not
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this keyword.
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Enterprise Social Keyword
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedGenericModelReferenceList'
          description: ''
      summary: Api enterprise social keyword protecting list
      x-summary-source: derived
components:
  schemas:
    PaginatedGenericModelReferenceList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/GenericModelReference'
        timestamp:
          type: string
          format: date-time
    Keyword:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 64
        label:
          type: string
          readOnly: true
        description:
          type: string
        parent:
          type: integer
          readOnly: true
        numchild:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        full_name:
          type: string
          description: 'Returns a string representation of a tree node and it''s ancestors,

            e.g. ''Cuisine > Asian > Chinese > Catonese''.'
          readOnly: true
      required:
      - created_at
      - full_name
      - label
      - name
      - numchild
      - parent
      - updated_at
    PatchedKeyword:
      type: object
      description: "Moves `UniqueValidator`'s from the validation stage to the save stage.\nIt solves the problem with nested validation for unique fields on update.\n\nIf you want more details, you can read related issues and articles:\nhttps://github.com/beda-software/drf-writable-nested/issues/1\nhttp://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers\n\nExample of usage:\n```\n    class Child(models.Model):\n    field = models.CharField(unique=True)\n\n\nclass Parent(models.Model):\n    child = models.ForeignKey('Child')\n\n\nclass ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):\n    class Meta:\n        model = Child\n\n\nclass ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):\n    child = ChildSerializer()\n\n    class Meta:\n        model = Parent\n```\n\nNote: `UniqueFieldsMixin` must be applied only on the serializer\nwhich has unique fields.\n\nNote: When you are using both mixins\n(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)\nyou should put `UniqueFieldsMixin` ahead."
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 64
        label:
          type: string
          readOnly: true
        description:
          type: string
        parent:
          type: integer
          readOnly: true
        numchild:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        full_name:
          type: string
          description: 'Returns a string representation of a tree node and it''s ancestors,

            e.g. ''Cuisine > Asian > Chinese > Catonese''.'
          readOnly: true
    GenericModelReference:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        model:
          type: string
        name:
          type: string
      required:
      - model
      - name
    PaginatedKeywordList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Keyword'
        timestamp:
          type: string
          format: date-time
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
