openapi: 3.2.0
info:
  title: Tandoor User File API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: User File
paths:
  /api/user-file/:
    get:
      operationId: apiUserFileList
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: query
        name: limit
        schema:
          type: string
        description: limit number of entries to return
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: query
        schema:
          type: string
        description: lookup if query string is contained within the name, case insensitive
      - in: query
        name: random
        schema:
          type: string
        description: randomly orders entries (only works together with limit)
      - in: query
        name: updated_at
        schema:
          type: string
        description: if model has an updated_at timestamp, filter only models updated at or after datetime
        examples:
          DateFormat:
            value: '1972-12-05'
            summary: Date Format
      tags:
      - User File
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserFileList'
          description: ''
      summary: Api user file list
      x-summary-source: derived
    post:
      operationId: apiUserFileCreate
      description: logs request counts to redis cache total/per user/
      tags:
      - User File
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserFile'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFile'
          description: ''
      summary: Api user file create
      x-summary-source: derived
  /api/user-file/{id}/:
    get:
      operationId: apiUserFileRetrieve
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user file.
        required: true
      tags:
      - User File
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFile'
          description: ''
      summary: Api user file retrieve
      x-summary-source: derived
    put:
      operationId: apiUserFileUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user file.
        required: true
      tags:
      - User File
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserFile'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFile'
          description: ''
      summary: Api user file update
      x-summary-source: derived
    patch:
      operationId: apiUserFilePartialUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user file.
        required: true
      tags:
      - User File
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserFile'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFile'
          description: ''
      summary: Api user file partial update
      x-summary-source: derived
    delete:
      operationId: apiUserFileDestroy
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user file.
        required: true
      tags:
      - User File
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api user file destroy
      x-summary-source: derived
  /api/user-file/{id}/cascading/:
    get:
      operationId: apiUserFileCascadingList
      description: get a paginated list of objects that will be cascaded (deleted) when deleting the selected object
      parameters:
      - in: query
        name: cache
        schema:
          type: boolean
          default: true
        description: If results can be cached or not
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user file.
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - User File
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedGenericModelReferenceList'
          description: ''
      summary: Api user file cascading list
      x-summary-source: derived
  /api/user-file/{id}/nulling/:
    get:
      operationId: apiUserFileNullingList
      description: get a paginated list of objects where the selected object will be removed whe its deleted
      parameters:
      - in: query
        name: cache
        schema:
          type: boolean
          default: true
        description: If results can be cached or not
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user file.
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - User File
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedGenericModelReferenceList'
          description: ''
      summary: Api user file nulling list
      x-summary-source: derived
  /api/user-file/{id}/protecting/:
    get:
      operationId: apiUserFileProtectingList
      description: get a paginated list of objects that are protecting the selected object form being deleted
      parameters:
      - in: query
        name: cache
        schema:
          type: boolean
          default: true
        description: If results can be cached or not
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user file.
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - User File
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedGenericModelReferenceList'
          description: ''
      summary: Api user file protecting list
      x-summary-source: derived
components:
  schemas:
    PaginatedGenericModelReferenceList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/GenericModelReference'
        timestamp:
          type: string
          format: date-time
    PatchedUserFile:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        file:
          type: string
          format: uri
          writeOnly: true
        file_download:
          type: string
          readOnly: true
        preview:
          type: string
          readOnly: true
        file_size_kb:
          type: integer
          readOnly: true
        created_by:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
    UserFile:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        file:
          type: string
          format: uri
          writeOnly: true
        file_download:
          type: string
          readOnly: true
        preview:
          type: string
          readOnly: true
        file_size_kb:
          type: integer
          readOnly: true
        created_by:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - created_by
      - file_download
      - file_size_kb
      - name
      - preview
    PaginatedUserFileList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/UserFile'
        timestamp:
          type: string
          format: date-time
    User:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        display_name:
          type: string
          readOnly: true
        is_staff:
          type: boolean
          readOnly: true
          title: Staff status
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          readOnly: true
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
        is_active:
          type: boolean
          readOnly: true
          title: Active
          description: Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
      required:
      - display_name
      - is_active
      - is_staff
      - is_superuser
      - username
    GenericModelReference:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        model:
          type: string
        name:
          type: string
      required:
      - model
      - name
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
