openapi: 3.2.0
info:
  title: Tandoor Meal Plan API
  version: 0.0.0 (2.6.13)
  x-logo:
    url: /static/assets/brand_logo.svg
    backgroundColor: '#FFFFFF'
    altText: Tandoor logo
    href: /
  description: Tandoor API Docs
tags:
- name: Meal Plan
paths:
  /api/meal-plan/:
    get:
      operationId: apiMealPlanList
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: query
        name: from_date
        schema:
          type: string
        description: Filter meal plans from date (inclusive). If nothing is given its today - 90 days.
        examples:
          DateFormat:
            value: '1972-12-05'
            summary: Date Format
      - in: query
        name: meal_type
        schema:
          type: array
          items:
            type: string
        description: Filter meal plans with MealType ID. For multiple repeat parameter.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: to_date
        schema:
          type: string
        description: Filter meal plans to date (inclusive). If nothing is given its today + 360 days.
        examples:
          DateFormat:
            value: '1972-12-05'
            summary: Date Format
      tags:
      - Meal Plan
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMealPlanList'
          description: ''
      summary: Api meal plan list
      x-summary-source: derived
    post:
      operationId: apiMealPlanCreate
      description: logs request counts to redis cache total/per user/
      tags:
      - Meal Plan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealPlan'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MealPlan'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MealPlan'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealPlan'
          description: ''
      summary: Api meal plan create
      x-summary-source: derived
  /api/meal-plan/{id}/:
    get:
      operationId: apiMealPlanRetrieve
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this meal plan.
        required: true
      tags:
      - Meal Plan
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealPlan'
          description: ''
      summary: Api meal plan retrieve
      x-summary-source: derived
    put:
      operationId: apiMealPlanUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this meal plan.
        required: true
      tags:
      - Meal Plan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealPlan'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MealPlan'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MealPlan'
        required: true
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealPlan'
          description: ''
      summary: Api meal plan update
      x-summary-source: derived
    patch:
      operationId: apiMealPlanPartialUpdate
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this meal plan.
        required: true
      tags:
      - Meal Plan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMealPlan'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMealPlan'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMealPlan'
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealPlan'
          description: ''
      summary: Api meal plan partial update
      x-summary-source: derived
    delete:
      operationId: apiMealPlanDestroy
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this meal plan.
        required: true
      tags:
      - Meal Plan
      security:
      - ApiKeyAuth: []
      responses:
        '204':
          description: No response body
      summary: Api meal plan destroy
      x-summary-source: derived
  /api/meal-plan/ical/:
    get:
      operationId: apiMealPlanIcalRetrieve
      description: logs request counts to redis cache total/per user/
      parameters:
      - in: query
        name: from_date
        schema:
          type: string
        description: Filter meal plans from date (inclusive). If nothing is given its today - 90 days.
        examples:
          DateFormat:
            value: '1972-12-05'
            summary: Date Format
      - in: query
        name: meal_type
        schema:
          type: array
          items:
            type: string
        description: Filter meal plans with MealType ID. For multiple repeat parameter.
      - in: query
        name: to_date
        schema:
          type: string
        description: Filter meal plans to date (inclusive). If nothing is given its today + 360 days.
        examples:
          DateFormat:
            value: '1972-12-05'
            summary: Date Format
      tags:
      - Meal Plan
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          content:
            text/calendar:
              schema:
                type: string
          description: ''
      summary: Api meal plan ical retrieve
      x-summary-source: derived
components:
  schemas:
    PatchedMealPlan:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        title:
          type: string
          maxLength: 64
        recipe:
          allOf:
          - $ref: '#/components/schemas/RecipeOverview'
        servings:
          type: number
          format: double
        note:
          type: string
        note_markdown:
          type: string
          readOnly: true
        from_date:
          type: string
          format: date-time
        to_date:
          type: string
          format: date-time
        meal_type:
          $ref: '#/components/schemas/MealType'
        created_by:
          type: integer
          readOnly: true
        recipe_name:
          type: string
          readOnly: true
        meal_type_name:
          type: string
          readOnly: true
        shopping:
          type: boolean
          readOnly: true
        addshopping:
          type: boolean
          writeOnly: true
    RecipeOverview:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        description:
          type:
          - string
          - 'null'
          maxLength: 512
        image:
          type:
          - string
          - 'null'
          format: uri
          readOnly: true
        keywords:
          type: array
          items:
            $ref: '#/components/schemas/KeywordLabel'
          readOnly: true
        working_time:
          type: integer
          readOnly: true
        waiting_time:
          type: integer
          readOnly: true
        created_by:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        internal:
          type: boolean
          readOnly: true
        private:
          type: boolean
        servings:
          type: integer
          readOnly: true
        servings_text:
          type: string
          readOnly: true
        rating:
          type:
          - number
          - 'null'
          format: double
          readOnly: true
        last_cooked:
          type:
          - string
          - 'null'
          format: date-time
          readOnly: true
        new:
          type: boolean
          readOnly: true
        recent:
          type: string
          readOnly: true
      required:
      - created_at
      - created_by
      - image
      - internal
      - keywords
      - last_cooked
      - name
      - new
      - rating
      - recent
      - servings
      - servings_text
      - updated_at
      - waiting_time
      - working_time
    MealType:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        name:
          type: string
          maxLength: 128
        order:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        time:
          type:
          - string
          - 'null'
          format: time
        color:
          type:
          - string
          - 'null'
          maxLength: 7
        created_by:
          type: integer
          readOnly: true
      required:
      - created_by
      - name
    KeywordLabel:
      type: object
      properties:
        id:
          type: integer
          readOnly: false
        label:
          type: string
          readOnly: true
      required:
      - label
    PaginatedMealPlanList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/MealPlan'
        timestamp:
          type: string
          format: date-time
    MealPlan:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        title:
          type: string
          maxLength: 64
        recipe:
          allOf:
          - $ref: '#/components/schemas/RecipeOverview'
        servings:
          type: number
          format: double
        note:
          type: string
        note_markdown:
          type: string
          readOnly: true
        from_date:
          type: string
          format: date-time
        to_date:
          type: string
          format: date-time
        meal_type:
          $ref: '#/components/schemas/MealType'
        created_by:
          type: integer
          readOnly: true
        recipe_name:
          type: string
          readOnly: true
        meal_type_name:
          type: string
          readOnly: true
        shopping:
          type: boolean
          readOnly: true
        addshopping:
          type: boolean
          writeOnly: true
      required:
      - created_by
      - from_date
      - meal_type
      - meal_type_name
      - note_markdown
      - recipe_name
      - servings
      - shopping
    User:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: false
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        display_name:
          type: string
          readOnly: true
        is_staff:
          type: boolean
          readOnly: true
          title: Staff status
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          readOnly: true
          title: Superuser status
          description: Designates that this user has all permissions without explicitly assigning them.
        is_active:
          type: boolean
          readOnly: true
          title: Active
          description: Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
      required:
      - display_name
      - is_active
      - is_staff
      - is_superuser
      - username
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
